apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealership-app
  template:
    metadata:
      labels:
        app: dealership-app
    spec:
      containers:
      - name: dealership-app
        image: dealership-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: dealership-service
spec:
  selector:
    app: dealership-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
